### ISSUE TITLE
Encrypt files

### ISSUE THREAD

**Issue by thanasisk** [5sw/Decrypt#1]
Hello - Decrypt works fine however, after editing the files I have no way to recompress/reencrypt them again and add them to my modem with my new settings. Is an encryptor in the pipeline? Cheers!

**Comment by 5sw** [comment]
Shouldn't be too hard to implement. I don't have this router any more though, so I won't be able to test this. If you do the testing I'd be happy to implement that feature though. I'm glad someone is finding this useful.

**Comment by thanasisk** [comment]
Sure, I'' do the testing for you. Any ideas on how to dump the flash or enable ssh are more than welcome. I have found a way to set the ftp/login/SMB passwords to known values.

**Comment by 5sw** [comment]
Implemented an additional tool "Encrypt" to encrypt files. Decrypting them with Decrypt works and yields the exact same file. 

Can be tested by encrypting the Encrypt binary itself, for example:

```
  ./Encrypt Encrypt abc
  ./Decrypt abc def
  diff -s Encrypt def
```
